### ISSUE TITLE
Web ideas!

### ISSUE THREAD

**Issue by JollyJolli** [hackpurrin/jackpurrin.me#3]
I hope you remember me! I was reviewing your web again to see if I could help again. I got a list of things that you can add to, im willing to help if you need to.

- Add more SEO data (OG Types, meta data, etc)
- Add analitycs (Google Analitycs works good)
- Add Loading Optimization

I can make all this if you want. I hope this helps, have a nice day <3

**Comment by hackpurrin** [comment]
I dunno if this link works, but according to [Pingdom](https://tools.pingdom.com/#64d02f4901800000) I need expiry headers?How do I add those if my website is protected with Cloudflare? I think they are enabled, but it doesn't say so.
Also, it it possible to compress the page with gzip or is that not able to work on Github Pages?
I've gotten analytics to work, and I am also working on SEO data.

**Comment by JollyJolli** [comment]
1.- Im not sure about that, cloudflare is great, but let me investigate a little bit.

2.- to compress the web you can minify the CSS, JS and HTML! (Just search in google [Css Minify](https://www.toptal.com/developers/cssminifier))

3.- That's perfect my friend! 🫶🏻

**Comment by JollyJolli** [comment]
Also an alternative of Pingdom you can use Lighthouse!
Go to you website, open the inspect tools, and go to Lighthouse, I think it does the same as Pingdom, I have never use it, maybe it is better idk
![image](https://github.com/user-attachments/assets/7fc19849-0bf5-40e7-b126-96a6302c73bf)

**Comment by JollyJolli** [comment]
So Just keep it like it is right now

**Comment by hackpurrin** [comment]
[👍 i got the expiry headers from this website.](https://cloudkul.com/blog/cloudflare-cache-purge-and-expire-headers/)

**Comment by JollyJolli** [comment]
Perfect! So the web is more optimized now! That great!

**Comment by hackpurrin** [comment]
![I've gotten it to 100 100 100 100! I found out that you can use GL with a Zen Browser (Firefox) extension.](https://github.com/user-attachments/assets/ae1f460e-cb32-45df-9b78-a46889d584fa)
I've gotten it to 100 100 100 100! I found out that you can use GL with a Zen Browser (Firefox) extension.

**Comment by JollyJolli** [comment]
Yo!!! Thats great 🫶🏻

**Comment by JollyJolli** [comment]
Do you have twitter or instagram? To see if we can make a project together

**Comment by jackpurrin** [comment]
Nah, I don't have a twitter nor do I have an insta.
What's the project? We can make a repo.

**Comment by JollyJolli** [comment]
I was thinking on a multipurpose website, like unit converter and things like that
